bridge:
  log_level: DEBUG
  name: iot-gateway-bridge
  version: 1.0.0
coap:
  observe_timeout_s: 300
  port: 5685
mqtt:
  connect_topic: v1/gateway/connect
  disconnect_topic: v1/gateway/disconnect
  host: localhost
  password: ''
  port: 1884
  rpc_topic: v1/gateway/rpc
  telemetry_topic: v1/gateway/telemetry
  username: ''
mqtt_mode: direct
device_tokens:
  NODO-SENSOR-1: "ZdB5zd3uPRAZ0LU4eU2P"
  NODO-SENSOR-2: "jqD4lGlOrtPTdz0KN76J"
  NODO-SENSOR-3: "ycWctfM6SHZLmFIR6ZtC"
otbr:
  enabled: false
  rest_api: http://localhost:8081
  scan_interval_s: 30
