services:
  otbr:
    image: openthread/border-router:latest
    container_name: otbr
    network_mode: host
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /var/lib/otbr:/data
    environment:
      OT_RCP_DEVICE: "spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=1000000&skip-rcp-compatibility-check"
      OT_INFRA_IF: "wlan0"
      OT_THREAD_IF: "wpan0"
      OT_LOG_LEVEL: "7"
      OT_WEB_LISTEN_ADDR: "0.0.0.0"
      OT_WEB_LISTEN_PORT: 8080
      OT_REST_LISTEN_ADDR: "0.0.0.0"
      OT_REST_LISTEN_PORT: 8081

  mytbedge:
    restart: always
    image: "thingsboard/tb-edge:4.2.0EDGE"
    ports:
      - "8082:8080"
      - "1883:1883"
      - "5683-5688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-edge
      CLOUD_ROUTING_KEY: c6b234d4-285a-0cf1-6e06-0697317f94a0
      CLOUD_ROUTING_SECRET: jlxsa4k6ymmzgp0dfb9v
      CLOUD_RPC_HOST: 10.182.112.11
      CLOUD_RPC_PORT: 7070
      CLOUD_RPC_SSL_ENABLED: false
    volumes:
      - tb-edge-data:/data
      - tb-edge-logs:/var/log/tb-edge

  postgres:
    restart: always
    image: "postgres:16"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-edge-postgres-data:/var/lib/postgresql/data

volumes:
  tb-edge-data:
  tb-edge-logs:
  tb-edge-postgres-data:
