idf_component_register(
    SRCS
        "app_main.c"
        "thread_auto_join.c"
        "sensor_sim.c"
        "coap_handlers.c"
        "registration.c"
        "power_mgmt.c"
        "config.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_event
        esp_netif
        nvs_flash
        openthread
        vfs
        ot_examples_common
        espressif__esp_ot_cli_extension
        coap
        driver
        esp_timer
        esp_pm
)
