bridge:
  log_level: DEBUG
  name: iot-gateway-bridge
  version: 1.0.0
coap:
  observe_timeout_s: 300
  port: 5683
mqtt:
  connect_topic: v1/gateway/connect
  disconnect_topic: v1/gateway/disconnect
  host: localhost
  password: ''
  port: 1883
  rpc_topic: v1/gateway/rpc
  telemetry_topic: v1/gateway/telemetry
  username: MXGYfpiNFAhdNIiDtNB1
otbr:
  enabled: false
  rest_api: http://localhost:8081
  scan_interval_s: 30
